# Generated by Django 2.2.16 on 2020-09-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AiAnalysisLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(default=None, max_length=255, verbose_name='image_path')),
                ('success', models.CharField(default=None, max_length=255, verbose_name='success')),
                ('message', models.CharField(default=None, max_length=255, verbose_name='message')),
                ('_class', models.IntegerField(db_column='class', default=None, verbose_name='class')),
                ('confidence', models.DecimalField(decimal_places=4, default=None, max_digits=5, verbose_name='confidence')),
                ('request_timestamp', models.PositiveIntegerField(default=None, verbose_name='request_timestamp')),
                ('response_timestamp', models.PositiveIntegerField(default=None, verbose_name='request_timestamp')),
            ],
            options={
                'verbose_name_plural': 'AI解析ログ',
                'db_table': 'ai_analysis_log',
            },
        ),
    ]
