# Generated by Django 2.2.16 on 2020-09-24 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aianalysislog',
            name='_class',
            field=models.IntegerField(db_column='class', default=None, null=True, verbose_name='class'),
        ),
        migrations.AlterField(
            model_name='aianalysislog',
            name='confidence',
            field=models.DecimalField(decimal_places=4, default=None, max_digits=5, null=True, verbose_name='confidence'),
        ),
        migrations.AlterField(
            model_name='aianalysislog',
            name='image_path',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='image_path'),
        ),
        migrations.AlterField(
            model_name='aianalysislog',
            name='message',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='aianalysislog',
            name='request_timestamp',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='request_timestamp'),
        ),
        migrations.AlterField(
            model_name='aianalysislog',
            name='response_timestamp',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='request_timestamp'),
        ),
        migrations.AlterField(
            model_name='aianalysislog',
            name='success',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='success'),
        ),
    ]
